// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3781.Robot2015.subsystems;

import org.usfirst.frc3781.Robot2015.RobotMap;
import org.usfirst.frc3781.Robot2015.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class WeightLift extends Subsystem {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController weightLift = RobotMap.weightLiftWeightLift;
    DigitalInput weightBottom = RobotMap.weightLiftWeightBottom;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void weightLiftRaise ()
    {
    	this.weightLift.set(-1);
    }
    public void weightLiftLower ()
    {
    	this.weightLift.set(1);
    }
    public void weightLiftSet(double liftSpeed)
    {
    	this.weightLift.set(-liftSpeed);
    }
    
    public boolean isWeightLiftOnBottom()
    {
    	return !this.weightBottom.get(); //Opposite for some reason, so "not()" it to correct this
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new CmdWeightStop());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

