// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3781.Robot2015.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3781.Robot2015.Robot;

import penner.easing.EasingSine;

/**
 *
 */
public class  CmdAutoRobotSetOnly extends Command {

	private Timer _timer;
	double Kp = 0.03;
	
	double _duration = 4.5;
	
    public CmdAutoRobotSetOnly() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveBase);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        
        this._timer = new Timer();
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	//Reset the gyro's direction
    	Robot.driveBase.getMainGyro().reset();
    	
    	this._timer.reset();
    	this._timer.start();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double speed = EasingSine.easeInOut((float) this._timer.get(), 0f, 0.4f, (float) (this._duration));
    	Robot.driveBase.drive(-speed, -speed * (Robot.driveBase.getMainGyro().getAngle() * Kp));
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
       return (this._timer.get() >= this._duration);
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveBase.drive(0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	this.end();
    }
}
